qa/urls.py
from django.conf.urls import url
from . import views

app_name = 'qa'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login'),
    url(r'^logout_user/$', views.logout_user, name='logout'),
    url(r'^blog/$',views.blog,name='blog'),
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^(?P<tag_id>[0-9]+)/$', views.questions, name='questions'),
    url(r'^answers/(?P<question_id>[0-9]+)/$', views.answers, name='answers'),
    url(r'^userdetails/$', views.userdetails, name='userdetails'),
    url(r'^like/(?P<answer_id>[0-9]+)/$', views.like, name='like'),
    ]

qamvit/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from graphene_django.views import GraphQLView
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('qa.urls')),
    path("graphql", GraphQLView.as_view(graphiql=True)),
]

qa/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType

import datetime


class Userdetails(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    USN = models.CharField(max_length=100, primary_key=True)
    semester = models.IntegerField(max_length=1)
    name = models.CharField(max_length=50)
    branch = models.CharField(max_length=20)

    def __str__(self):
        return self.USN


class Tags(models.Model):
    tag_id = models.AutoField(default=None, primary_key=True)
    tag_name = models.CharField(max_length=50)
    no_of_questions = models.IntegerField(default=0)

    def __str__(self):
        return self.tag_name


class Comments(models.Model):
    text = models.TextField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    comment = GenericForeignKey()


class Questions(models.Model):
    question_tag = models.ForeignKey(
        Tags, on_delete=models.CASCADE, default=1, related_name='questions')
    user_usn = models.ForeignKey(Userdetails, on_delete=models.CASCADE)
    questionfield = models.CharField(max_length=200)
    no_of_answers = models.IntegerField(default=0)
    date = models.DateField(default=datetime.date.today())
    comments = GenericRelation(Comments, related_query_name='questions')

    def __str__(self):
        return self.questionfield


class Answers(models.Model):
    answer = models.CharField(max_length=1000)
    question = models.ForeignKey(
        Questions, related_name="questions_id", on_delete=models.CASCADE)
    likes = models.IntegerField(default=0)
    written_by = models.CharField(max_length=100)
    date = models.DateField(default=datetime.date.today())
    comments = GenericRelation(Comments, related_query_name='answers')

    def __str__(self):
        return self.written_by


class Blog(models.Model):
    author = models.CharField(max_length=100)
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=1000)
    user_details = models.ForeignKey(Userdetails, on_delete=models.CASCADE)
    comments = GenericRelation(Comments, related_query_name='blog')

    def __str__(self):
        return self.title


class Like(models.Model):
    answer_id = models.CharField(max_length=100)
    liked_user_usn = models.ForeignKey(Userdetails, on_delete=models.CASCADE)

    def __str__(self):
        return self.answer_id

qa/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import *

class UserdetailsForm(forms.ModelForm):

    class Meta:
        model = Userdetails
	# test
        fields = ['USN', 'name', 'branch', 'semester']
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
class QuestionForm(forms.ModelForm):

	class Meta:
		model=Questions
		fields=['questionfield']
class AnswerForm(forms.ModelForm):
	class Meta:
		model=Answers
		fields=['answer']

class BlogForm(forms.ModelForm):
    class Meta:
        model=Blog
        fields=['title','content']
class TagForm(forms.ModelForm):
    class Meta:
        model=Tags
        fields=['tag_name']

qa/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404,redirect,HttpResponseRedirect
from .forms import UserdetailsForm,UserForm,QuestionForm,AnswerForm,BlogForm,TagForm
from .models import *
from django.contrib import messages

def logout_user(request):

    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'qa/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                name=request.user.username
                tags=Tags.objects.all()
                recent_questions=Questions.objects.all().order_by('id').reverse()[:4]
                most_likes=Answers.objects.all().order_by('likes').reverse()[:4]
                context={
                    'tags':tags,
                    'questions':recent_questions,
                    'most_likes':most_likes,
                        }

                return render(request, 'qa/home.html', context)
            else:
                return render(request, 'qa/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'qa/login.html', {'error_message': 'Invalid login'})
    return render(request, 'qa/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/userdetails/')

    context = {
        "form": form,
    }
    return render(request, 'qa/register.html', context)


def home(request):
    if request.method=="POST":
            form=TagForm(request.POST or None)
            if form.is_valid():
                tag_names=form.cleaned_data['tag_name']
                a=Tags(tag_name=tag_names)
                a.save()
    if request.user.is_authenticated:
        recent_questions=Questions.objects.all().order_by('id').reverse()[:4]
        most_likes=Answers.objects.all().order_by('likes').reverse()[:4]
        
        tags=Tags.objects.all()
        context={
        'tags':tags,
        'questions':recent_questions,
        'most_likes':most_likes,
        }
        return render(request, 'qa/home.html',context)
    else:
        return render(request,'qa/login.html')
    
def blog(request):
    if request.method=="POST":
        form=BlogForm(request.POST or None)
        if form.is_valid():

            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            users=Userdetails.objects.filter(user=request.user)
            # print(request.user)
            for i in users:
                usn=i.USN
            a=Userdetails.objects.filter(USN=usn)
            for i in a:
                id_user=i.user_id
            a=Blog(author=usn,title=title,content=content,user_details_id=id_user)
            a.save()
            messages.success(request,"Thank you for writing blog!")
            tags=Tags.objects.all()
            recent_questions=Questions.objects.all().order_by('id').reverse()[:4]
            most_likes=Answers.objects.all().order_by('likes').reverse()[:4]
            context={
                    'tags':tags,
                    'questions':recent_questions,
                    'most_likes':most_likes,
                        }
            return render(request,'qa/home.html',context)
    else:

        if request.user.is_authenticated:
            form=BlogForm(request.POST or None)
            blogs=Blog.objects.all()
            context={
            'blogs':blogs,
            'form':form,
            }
            return render(request,'qa/blog.html',context)
        else:
            return render(request,'qa/login.html')



def questions(request,tag_id):
    if request.method == "POST":
        form=QuestionForm(request.POST or None)
        if form.is_valid():
            users=Userdetails.objects.filter(user=request.user)
            for i in users:
                usn=i.USN
            question=form.cleaned_data['questionfield']
            c=Questions(questionfield=question,question_tag=Tags.objects.get(tag_id=tag_id),
                user_usn=Userdetails.objects.get(USN=usn))
            c.save()
            t=Tags.objects.get(tag_id=tag_id)
            t.no_of_questions=t.no_of_questions+1
            t.save()
            messages.success(request,"Thank you for asking question!")
            tags=Tags.objects.all()
            recent_questions=Questions.objects.all().order_by('id').reverse()[:4]
            most_likes=Answers.objects.all().order_by('likes').reverse()[:4]
            context={
                    'tags':tags,
                    'questions':recent_questions,
                    'most_likes':most_likes,
                        }
            return render(request,'qa/home.html',context)
    else:

        if request.user.is_authenticated:
            question_list=Questions.objects.filter(question_tag_id=tag_id)
            form=QuestionForm(request.POST or None)
            tag_here=Tags.objects.filter(tag_id=tag_id)
            context={
            'question_list':question_list,
            'form':form,
            'tag_id':tag_id,
            'tag_here':tag_here,

            }
            return render(request,'qa/questions.html',context)
        else:
            return render(request,'qa/login.html')



def answers(request,question_id):
    if request.method == "POST":
        form=AnswerForm(request.POST or None)
        if form.is_valid():
            users=Userdetails.objects.filter(user=request.user)
            for i in users:
                usn=i.USN
            question_details=Questions.objects.filter(id=question_id)
            for k in question_details:
                question_usn=k.user_usn_id
            if(usn==question_usn):
                messages.success(request,"Sorry you cannot answer the question you asked!!!")
                tags=Tags.objects.all()
                recent_questions=Questions.objects.all().order_by('id').reverse()[:4]
                most_likes=Answers.objects.all().order_by('likes').reverse()[:4]
                context={
                            'tags':tags,
                            'questions':recent_questions,
                            'most_likes':most_likes,
                        }
                return render(request,'qa/home.html',context)
            else:
                answer=form.cleaned_data['answer']
                p=Answers(answer=answer,written_by=Userdetails.objects.get(USN=usn),question_id=question_id)
                p.save()
                messages.success(request,"Thank you for answering question!")
                tags=Tags.objects.all()

                recent_questions=Questions.objects.all().order_by('id').reverse()[:4]


                most_likes=Answers.objects.all().order_by('likes').reverse()[:4]

                context={
                'tags':tags,
                'questions':recent_questions,
                'most_likes':most_likes,
                }
                return render(request,'qa/home.html',context)
    else:
        if request.user.is_authenticated:
            answers_list=Answers.objects.filter(question_id=question_id)
            question_here=Questions.objects.filter(id=question_id)
            form=AnswerForm(request.POST or None)
            # form2=CommentForm(request.POST or None)
            context={
            'answers_list':answers_list,
            'form':form,
            # 'form2':form2,
            'question_here':question_here,
            }
            return render(request,'qa/answers.html',context)
        else:
            return render(request,'qa/login.html')


def userdetails(request):
    if request.method == "POST":
        form=UserdetailsForm(request.POST)
        if form.is_valid():
            USN=form.cleaned_data['USN']
            name=form.cleaned_data['name']
            semester=form.cleaned_data['semester']
            branch=form.cleaned_data['branch']
            p=Userdetails(USN=USN,name=name,semester=semester,branch=branch,user=request.user)
            p.save()
            tags=Tags.objects.all()
            recent_questions=Questions.objects.all().order_by('id').reverse()[:4]
            most_likes=Answers.objects.all().order_by('likes').reverse()[:4]
            context={
                    'tags':tags,
                    'questions':recent_questions,
                    'most_likes':most_likes,
                        }
            return render(request,'qa/home.html',context)
        else:
            form=UserdetailsForm(request.POST)
            context={
            'form':form,
            'messages':'USN already exists'
            }
            return render(request,'qa/userdetails.html',context)
    else:
        if request.user.is_authenticated:
            form=UserdetailsForm(request.POST or None)
            context={
            'form':form,
            }
            return render(request,'qa/userdetails.html',context)
        else:
            return render(request,'qa/login.html',{})


def like(request,answer_id):
    users=Userdetails.objects.filter(user=request.user)
    for i in users:
        usn=i.USN
    if Like.objects.filter(answer_id=answer_id,liked_user_usn=usn).exists():

qa/templates/qa/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MVIT{% endblock %}</title>
    {% load staticfiles %}
    
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'qa/static/css/style.css' %}"/>
    <script src="jquery-3.2.1.min.js"></script>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
    


    <script src="{% static 'qa/js/main.js' %}"></script>

<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Dialog - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#dialog" ).dialog();
  } );
  </script>
  <style type="text/css">
 /* #introduction {
  background: linear-gradient(rgba(100,181,246 ,1), rgba(0,0,0,0.8)), url('http://bit.ly/2fBj6OJ') 0% 0%/cover 
}*/
#userdetails {
  background: linear-gradient(rgba(237, 228, 184 ,1), rgba(0,0,0,0.8)),url('{% static 'images/collegeimage.jpg'%}') 0% 0%/cover 
}

 #introduction {
  background: linear-gradient(rgba(100,181,246 ,1), rgba(0,0,0,0.8)),url('{% static 'images/introduction.jpg'%}') 0% 0%/cover 
}
#blog{
  background: linear-gradient(rgba(100,181,246 ,1), rgba(0,0,0,0.8)), url('{% static 'images/blogimage.jpg'%}') 0% 0%/cover 
}
#profile{
  background: linear-gradient(rgba(100,181,246 ,1), rgba(0,0,0,0.8)), url('https://thumbs.dreamstime.com/z/web-blog-background-concept-glowing-12266066.jpg') 0% 0%/cover 
}

#questions{
  background: linear-gradient(rgba(100,181,246 ,1), rgba(0,0,0,0.8)), url('{% static 'images/questionsimage.jpg'%}') 0% 0%/cover 
}
#answers{
  background: url('') 0% 0%/cover
}
#tags {
  background: /*linear-gradient(rgba(100,181,246 ,1))*/
   url('{% static 'images/tagsimage.jpg'%}') 0% 0%/cover 
}


#info-3 {
  background: linear-gradient(rgba(100,181,246 ,0.3), rgba(0,0,0,0.8)),url("http://bit.ly/2xMHeVk") 0% 0%/cover;
}


#feature-rundown img {
  width: 120px;
}

/*-===== dev ===== */
.debug {
  border: 2px solid red;
}
/*============ Utility classes. 
 Use coolstrap for faster ease of development ============*/

.fill-viewport {
  min-height: 100vh
}
.fill-40-viewport {
  min-height: 40vh
}
.fill-80-viewport {
  min-height: 80vh
}
.fill-90-viewport {
  min-height: 90vh
}
.jumbotron-transparent {
  background-color: transparent
}
.text-white-70 {
  color: rgba(255,255,255,0.7)
}
.text-black-70 {
  color: rgba(0,0,0,0.7)
}
.text-black-40 {
  color: rgba(0,0,0,0.4)
}
.text-white-40 {
  color: rgba(255,255,255,0.4)
}
footer {
    padding: 60px 0;
    background-color:rgb(150,150,120) ;
}
#footer-info {
    width: 380px;
    float: left;
    margin-top: 10px;
}
#footer-links {
    width: 520px;
    float: right;
}
#footer-links ul {
    width: 150px;
    float: left;
    margin-left: 20px;
}
#footer-links ul li {
    margin: 10px 0;
}

/*== 1. 
  1. Borders along x an y
  2. Borders with colors i.e the shades of white and gray above
  3. Unordered list with borders all round
  4. Unordered list with borders along y, as in pricing table here
  5. Border size class*/

.list-border-y li {
  border-top: 1px solid
}
.list-border-y li:last-child {
  border-bottom: 1px solid
}
.list-border-black-20 li,
.list-border-black-20 li:last-child{
  border-color: rgba(0,0,0,0.2)
}

.wrapper {
    margin: 0 auto;
    padding: 0 10px;
    width: 940px;
    background-color: D0EAF2;

}


@media screen and (min-width: 768px ){
  /*need a 50% on medium devices and above */
  .w-md-50 {
    width: 50%
  }
  
  /*need to set flex-basis and have it dependent on size too
  usage tip: if you want the element to NOT be positioned in the
  center, add this class to a non `.container` div. Container divs in
  bootstrap are styled to seat in the center of the page. 
  */
  .basis-md-50 {
    flex-basis: 50%
  }  
}
</style>
  <script type="text/javascript">
  window.sr = ScrollReveal();
sr.reveal('.leadss');
sr.reveal('.leads2');
sr.reveal('.leads3');
</script>
<script type="text/javascript" src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>


</head>
<body>
<script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #27292d">

    <button> <a class="navbar-brand" href="{% url 'qa:home' %}">Q/A-MVIT</a></button>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <button> <a class="navbar-brand" href="{% url 'qa:home' %}">Home</a></button>
      </li>
      <li class="nav-item active">
        <button><a class="navbar-brand" href="{% url 'qa:blog' %}">Blog</a></button>
      </li>
      <li class="nav-item active">
        <button><a class="navbar-brand" href="{% url 'qa:profile' %}">Profile</a></button>
      </li>
      <li class="nav-item active">
        <button> <a class="nav-link navbar-brand" href="http://www.sirmvit.edu/">Official Site</a></button>
      </li>
      <li class="nav-item active">
        <button> <a class="nav-link navbar-brand" href="{% url 'qa:logout' %}"> Logout</a></button>
      </li>

    </ul>
     <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>

  
</nav>


<script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>

<script type="text/javascript">
window.sr = ScrollReveal();
sr.reveal('.foo', { duration: 200 });
</script>
{% block body %}
{% endblock %}
</body>
</html>

qa/templates/qa/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MVIT{% endblock %}</title>
    {% load staticfiles %}
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
   <style type="text/css">
     .fill-viewport {
  min-height: 100vh
}

#loginpage {
  background: linear-gradient(rgba(237, 228, 184 ,1), rgba(0,0,0,0.8)),url('{% static 'images/collegeimage.jpg'%}') 0% 0%/cover 
}
#register {
  background: linear-gradient(rgba(237, 228, 184 ,1), rgba(0,0,0,0.8)),url('{% static 'images/collegeimage.jpg'%}') 0% 0%/cover 
}
   </style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #27292d">

 <button> <a class="navbar-brand" href="{% url 'qa:home' %}">Q/A-MVIT</a></button>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <button> <a class="navbar-brand" href="{% url 'qa:register' %}">Register</a></button>
      </li>
  
        <button> <a class="nav-link navbar-brand" href="{% url 'qa:login' %}">&nbsp; Login</a></button>
      </li>

    </ul>
  </div>

  
</nav>
{% block body %}
{% endblock %}
</body>
</html>

qa/templates/qa/example.html
{% extends 'qa/base.html' %}
{% block body %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <h1{% if message.tags %} class="{{ message.tags }}"{% endif %} style="color: red"></h1>
    <div id="dialog" title="New message">
            <p>{{message}}</p>
    </div>
    {% endfor %}
</ul>
{% endif %}
</br>
<section id="introduction">
 <div class="container">
   <div class="row fill-viewport align-items-center">
     <div class="col-12 col-md-6">
       <h1 class="text-black" style='display:inline';>Welcome to Q/A MVIT</h1>
       <p class="lead text-white-70">
         Clarify your doubts by posting the questions related to your field and get answered by your Lecturers,Seniors and your fellow members.Moreover,write the blogs in the fields which you are interested in!
       </p>
       <a class="btn btn-primary" href="#tags" role="button">Let's Get Started!</a>
     </div>
   </div>
 </div>
</section>


<section id="tags">
  <div class="container">
    <div class="fill-80-viewport">
          <div>
              <h1 class="display-4 align-items=center"> List of all tags!</h1></br>
                <h5>Select the topics listed below!</h5>
          </div>
          <div class="container align-tems-center">
    
                {% if tags%}
              {% for tag in tags%}
          <a href="{%url 'qa:questions' tag.tag_id%}" class="btn btn-primary scrollreveal">{{tag}}<span class="badge badge-light"> .</span></a>

              <script type="text/javascript">
                sr.reveal('.leadss')
          </script>

              {% endfor %}
              {% endif %}
        </div>
  </div>
</div>
</section>

<section id="recent questions">
  <div class="container">
  <div class="row">
    <div class="col">


        <h1 style="color: orange">Recent questions</h1>
          <div class="jumbotron leadss">
              {%if questions%}
      {%for i in questions%}
    <p class="leads3">
  <ul>
              <li><a href="{%url 'qa:answers' i.id %}">{{i.questionfield}}</a></li>
  </ul>
</p>
{% endfor %}
{% endif %}
</div>
</div>
 <div class="col">
<h1 style="color: pink">Most liked answers</h1>
<div class="jumbotron ">

{%if most_likes%}
{%for i in most_likes%}
<p class="leads2">
<ul>
<li><a href="{%url 'qa:answers' i.question_id %}">{{i.answer}}</a>  written by<strong>{{i.written_by}}</strong></li>
</ul>
</p>
{% endfor %}
{% endif %}
</div>
</div>
</div>

</section>

<section id="footer" class="bg-dark">
  <div class="container">

    <h2>All rights reserved!

             </div>
    
    </h2>
    </div>
</section>

{% endblock %}

qa/templates/qa/login.html
{% extends 'qa/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<section id="loginpage">
<div class="container-fluid">
<div class="container " style="margin-left: 500px;">
    <div class="row fill-viewport">
        
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                </br></br></br></br></br></br></br>
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p style="color: red"><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'qa:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="input col-sm-2" for="id_username">
                                
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text" placeholder="Username">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                            
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password" placeholder="Password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer" style="color:white">
                    Don't have an account? <a href="{% url 'qa:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>

</section>
{% endblock %}